
// This file was auto-generated by ML.NET Model Builder. 

using SentimentAnalysisNLP;

// Create single instance of sample data from first line of dataset for model input
MLModel3.ModelInput sampleData = new MLModel3.ModelInput()
{
    Col0 = @"i feel like an idiotic herd mentality mindless follower when i m walking down the street with a large group of people",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Col2 with predicted Col2 from sample data...\n\n");


Console.WriteLine($"Col0: {@"i feel like an idiotic herd mentality mindless follower when i m walking down the street with a large group of people"}");
Console.WriteLine($"Col2: {3F}");


var sortedScoresWithLabel = MLModel3.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

