
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp2;
Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");

// ask user to enter input data
Console.WriteLine("Enter string to analyze: ");
string? input = Console.ReadLine();

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Col0 = @input,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine($"\n\nPredicted Emotion: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

